apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  labels:
    tags.datadoghq.com/version: {{ .Values.image.tag | quote }}
    tags.datadoghq.com/service: {{ .Values.dd_service | quote }}
    tags.datadoghq.com/env: {{ .Values.env | quote }}  
    {{- include "labels" . | nindent 4 }}
  annotations:
    json_logs: 'true'
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: {{ .Values.image.tag | quote }}
        tags.datadoghq.com/service: {{ .Values.dd_service | quote }}
        tags.datadoghq.com/env: {{ .Values.env | quote }}      
        {{- include "selectorLabels" . | nindent 8 }}
        antiaffinitykey: {{ include "fullname" . }}
      annotations:
        json_logs: 'true'
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - {{ .Values.platform }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: antiaffinitykey
                  operator: In
                  values:
                  - {{ include "name" . }}
              topologyKey: "topology.kubernetes.io/zone"
      volumes:
        - name: appsettingsjson
          secret:
            secretName: {{ include "fullname" . }}-appsettings
            defaultMode: 0777
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath 
      serviceAccountName: {{ .Values.serviceAccountName}}
      containers:
        - name: service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort}}
          volumeMounts:
          - name: appsettingsjson
            mountPath: /app/{{ .Values.mountPath }}
            subPath: {{ .Values.mountPath }}
          - name: apmsocketpath
            mountPath: /var/run/datadog  
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment }}
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_TRACE_AGENT_URL
              value: 'unix:///var/run/datadog/apm.socket'
            - name: DD_TAGS
              value: "nbly_app_id=shr"
            - name: logger_level
              value: "Information"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
